site_name: Sharepicgenerator
nav:
  - Einleitung: index.md
  - Was ist ein Sharepic: was.md
  - Wie kann ich ein Sharepic erstellen: wie.md
  - Tabellen erstellen: markdown.md
  - Profieinstellungen: profi.md
  - Verbindung zur gr√ºnen Wolke (Cloud): cloud.md
  - Code-API: code.md
theme:
  name: null
  custom_dir: 'theme/'
  static_templates:
    - 404.html

  include_search_page: true
  search_index_only: false

  highlightjs: true
  hljs_languages: []

  include_homepage_in_sidebar: true
  prev_next_buttons_location: bottom
  navigation_depth: 4
  titles_only: false
  sticky_navigation: true
  collapse_navigation: true
site_dir: ../code/dist/documentation
extra_css:
  - extra.css
use_directory_urls: true
plugins:
  - search:
      lang: de
#dev_addr: '0.0.0.0:8080' # local only

